### PR TITLE
[OK TO MERGE] [phase 3b done] 2nd database and comparison tests fixed

### LINKED ISSUE #8: write data generation script - 10+ million records for secondary database

### LINKED ISSUE #10: verify that all read queries used by your API will run in under 50ms for both systems

### LINKED ISSUE #11: compare performance of both systems, select one for final implementation

### PR DESCRIPTION
**Pull request by cjm771**
resolves #8
resolves #10 
resolves #11

- [x] after cassandra installed, seeding and api can be ran as thing below. see README log for installation notes. 
- [x] 10million seeded in 2nd database
- [x] api / tests work. request under 40ms.
- [x] gist for both should be like so: 

``` sh
# for 10 million records each for reviews and ratings..
# postgres do.. 
$> npm run megaseed --db=psql
# cassandra do.. 
$> npm run megaseed --db=cassandra
# similarly for starting up node
# postgres do.. 
$> npm start --db=psql
# cassandra do.. 
$> npm start --db=cassandra
```

image

image

### CODE REVIEW

File: db/cassandra.js [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+// Connecting DB
+const client = new cassandra.Client({
+  contactPoints: ['127.0.0.1'], 
+  keyspace: process.env.CASSANDRA_DB_NAME,
+  localDataCenter: 'datacenter1'
+});
+
+// DB functions
+module.exports = {
+  queryDB: function(query) {
```
Comment (allenhsieh) [inline db/cassandra.js]: Not a suggestion but question for my own learning, is there a best practice for arrow functions?  I notice you use function() here and then an arrow function the next line, could this also be an arrow?

Comment (cjm771) [reply db/cassandra.js]: true could be consistent

File: README.md [hunk 2]
```diff
@@ -23,6 +23,8 @@
   - [1.5. Log](#15-log)
     - [1.5.1. Development setup (+ Refactoring)](#151-development-setup--refactoring)
     - [1.5.2. Million Records (2 Tables of 10million)](#152-million-records-2-tables-of-10million)
+    - [1.5.3. Second Database](#153-second-database)
+    - [1.5.4. Comparison](#154-comparison)
 
 <!-- /TOC -->
 ## 1.3. Usage
```
Comment (allenhsieh) [inline README.md]: It might be good to break off the usage into subections, one for postgres and one for cassandra. i had to `cd ..` to get out of the client folder to run mega seed

File: README.md [hunk 3]
```diff
@@ -78,12 +80,16 @@ $> cd client/ && npm install
...
 # create the db with `createdb` command
 $> createdb firebnb-reviews
 # seed  db,make sure you ahve your credentials in your .env
 $> npm run seed-database
-# for 10 million records each for reviews and ratings..do 
+# Pfor 10 million records each for reviews and ratings..
+# postgres do.. 
 $> npm run megaseed
+# cassandra do.. 
+$> npm run megaseed --db=cassandra
```
Comment (allenhsieh) [inline README.md]: `npm run megaseed --db=cassandra` should this be `npm run megaseedCasandra` instead?

File: dummydata/megaseed.js [hunk 4]
```diff
@@ -1,73 +1,288 @@
...
   return __dirname + '/' + name;
 }
-
-const writeCSV = async (name, contents) => {
+ 
+const writeFile = async (name, contents) => {
+  if (name.indexOf('/') !== -1) {
+    const dir = __dirname + '/' + name.split('/').slice(0, -1).join('/');
+    await Promise.promisify(fs.stat)(dir).catch(async (err) => {
+      if (err && err.errno === 34) {
```
Comment (allenhsieh) [inline dummydata/megaseed.js]: we debugged together but `err.errno === 34` causes a bug (it returned -2 on my computer)

File: db/cassandra.js (hunk 1 above)
Comment (cjm771) [reply db/cassandra.js]: the reason was because I inherited the code and i use fat arrows usually. there is a use case where if you wanted to use the `this` statement in reference to the object literal its housed in and use other methods. this in a fat arrow is inherited from its scope.

File: README.md (hunk 2 above)
Comment (cjm771) [reply README.md]: I added two seperate areas in installation section, thanks

image

File: README.md (hunk 3 above)
Comment (cjm771) [reply README.md]: ohhhh good catch.. yes confused myself with `node megaseed --db=cassandra being the commmand`

also added the env notes in installation area.

File: README.md [hunk 5]
```diff
@@ -176,4 +184,135 @@ require('dotenv').config({path: path.resolve(__dirname + '/../.env')});
...
+To start I Installed and tested by doing the following. THis tutorial also was very nice : [Cassandra Tutorial from tutorialspoint](https://www.tutorialspoint.com/cassandra/cassandra_introduction.htm)
+
+
+**Note: if in your python shell the arrow keys print characters when typed..you might need to create a symlink to readline lib that your have something like: `ln /usr/local/opt/readline/lib/libreadline.dylib /usr/local/opt/readline/lib/libreadline.7.dylib`
+``` sh
+# latest python (if dont have)
+$> brew install python
+# cassandra shell
+$> pip install cql
+# start it up
```
[the remark this answers is not in the document]
Comment (cjm771) [reply README.md]: yup updated in readme.

[the remark this answers is not in the document]
Comment (cjm771) [reply README.md]: got it! thanks! added that.

**Comment by cjm771** [comment]
made changes take a look if they meet criteria

File: db/cassandra.js [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+        if (err) {
+          reject(err);
+        } else {
+          resolve(res.rows);
+        }
+      });
+    });
+  },
+  getReviewsById: function(id) {
+    const queryStr = `SELECT * FROM reviews WHERE property_id=${id}`;
```
Comment (allenhsieh) [inline db/cassandra.js]: BUG: should be id=${id}
